from pathlib import Path


ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

PRIMARY_COLOR = '#FE7689'
DARKER_PRIMARY_COLOR = '#F25E86'
DARKEST_PRIMARY_COLOR = '#F24194'

BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 10
MINIMUN_WIDTH = 350